import type { Metadata } from "next";
import "./globals.css";
import DashboardWrapper from "./DashboardWrapper";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Project Management Tool",
  description: "Generated by Michael Lee",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <DashboardWrapper>{children}</DashboardWrapper>
        <Toaster />
      </body>
    </html>
  );
}
